Clarify usage of `WorkerPlugin` in `webpack.config.js`
I followed the instructions in the README and encountered the following error:

```js
ReferenceError: WorkerPlugin is not defined
```

I am not familiar with WebPack, so I basically copy-pasted from https://webpack.js.org/ and your documentation. However, it seems like adding the following at the top of `webpack.config.js` resolves this issue:

```js
const WorkerPlugin = require('worker-plugin');
```

This updates the README to make this more clear.